# Generated by Django 3.1.7 on 2021-03-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='role',
        ),
    ]
